# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bb35902ffc773851346b6154010a8c6f755d6e2bc21f79cb08def5d328b798cb3f43bfbf8bd8212da1d922ba3816ffa72d78beac5fb1b7fab1960c774d9eae4

test:
  secret_key_base: 4c1eefd339255e74829d6c22624b63fd23286f1207d543e80f5d483bd513c4e75827623110ad77e6c73f9f4502b5689ece5d2e8d207d106ce5ff2c9f9dd165b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
